import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import HeaderWrapper from '@/components/header-wrapper';
import FooterWrapper from '@/components/footer-wrapper';
import ReactQueryProvider from '@/components/react-query-provider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Auctioners',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en" className="scroll-smooth">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <HeaderWrapper />
          {children}
          <FooterWrapper />
          <ReactQueryDevtools initialIsOpen={false} />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
